### ISSUE TITLE
！！

### ISSUE THREAD

**Issue by n5xxxx** [lovechoudoufu/about_cobaltstrike4.4_cdf#3]
之前看到issue看到关于vnc的斧正
忘记了 师傅能在说下吗

**Comment by lovechoudoufu** [comment]
把其他版本cs目录下的那个放vnc的目录复制过来就好了发自我的鸿蒙OS-------- 原始邮件 --------发件人： 南5 ***@***.***>日期： 2022年6月3日周五 18:42收件人： "lovechoudoufu/about_cobaltstrike4.4_cdf" ***@***.***>抄送： Subscribed ***@***.***>主    题： [lovechoudoufu/about_cobaltstrike4.4_cdf] ！！ (Issue #3)

之前看到issue看到关于vnc的斧正

忘记了 师傅能在说下吗
